name: Build & Deploy (Netlify)

on:
    workflow_dispatch:
        inputs:
            run_deploy:
                description: "Deploy to Netlify? (true/false)"
                required: false
                default: "true"
    schedule:
        # 6:00 AM America/Chicago (Central) on Tuesdays = 11:00 UTC
        - cron: "0 11 * * TUE"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: |
                      package-lock.json
                      site/package-lock.json

            # Install a system Chrome and expose CHROME_PATH
            - name: Install Google Chrome
              uses: browser-actions/setup-chrome@v1
              with:
                  chrome-version: stable

            - name: Install root deps (if present)
              run: |
                  if [ -f package-lock.json ]; then npm ci; fi

            - name: Install site deps (incl. dev)
              run: |
                  cd site
                  npm ci --include=dev

            # Build + run data scripts via your existing root script
            - name: Build site (runs data scripts + SvelteKit build)
              env:
                  # Make sure your scraper can find Chrome
                  CHROME_PATH: ${{ env.CHROME_PATH }}
                  NODE_ENV: production
              run: |
                  npm run build-site

            # Commit only generated data (never the build output)
            - name: Commit updated data (if any)
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  git add \
                    site/src/data/trades/trades-current-year.json \
                    site/src/data/standings/standings-current-year.json \
                    site/src/data/drafts/dynasty-rankings.json || true

                  if ! git diff --cached --quiet; then
                    git commit -m "chore(ci): update generated data (trades/standings/rankings) [skip ci]"
                    git push
                  else
                    echo "No data changes to commit."
                  fi

            - name: Upload build artifact (optional)
              uses: actions/upload-artifact@v4
              with:
                  name: site-build
                  path: site/build

            - name: Deploy to Netlify
              if: ${{ github.event_name == 'schedule' || github.event.inputs.run_deploy != 'false' }}
              run: |
                  npx --yes netlify-cli deploy --dir=site/build --prod --site="$NETLIFY_SITE_ID"
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
